'features':
    # insider trading features
    - 'n_sales'
    - 'n_purch'
    - 'insider_balance'
    # volume features
    - 'volume_ma20'
    - 'volume_ma50'
    - 'volume_ratio'
    # volatility features
    - 'vol_qoq'
    - 'vol_yoy'
    - 'downside_vol_qoq'
    - 'downside_vol_yoy'
    - 'downside_risk_ratio_qoq'
    - 'downside_risk_ratio_yoy'
    - 'rel_vol_month'
    - 'rel_vol_quarter'
    - 'rel_vol_year'
    # price growth features
    - 'price_mom'
    - 'price_qoq'
    - 'price_yoy'
    - 'price_2y'
    - 'price_risk_quarter'
    - 'price_risk_semester'
    - 'price_risk_year'
    # technical features
    - 'rsi_14d'
    - 'rsi_90d'
    - 'momentum_month'
    - 'momentum_quarter'
    - 'momentum_year'
    - 'momentum_2year'
    - 'ma20_distance'
    - 'ma50_distance'
    # market trend features
    - 'index_qoq'
    - 'index_sos'
    - 'index_yoy'
    - 'index_2y'
    - 'fear_ma30'
    - 'high_fear'
    - 'low_fear'
    # financial features
    - 'gpm'
    - 'roa'
    - 'roe'
    - 'ebitdam'
    - 'size'
    - 'earnings_vol'
    - 'margin_vol'
    - 'days_since_earnings'
    # price - valuation
    - 'mkt_cap'
    - 'earn_drift'
    - 'pe'
    - 'pb'
    - 'ps'
    - 'ev_ebitda'
    - 'f_score'
    # sector features
    - 'pe_sec'
    - 'momentum_sec_yoy'
    - 'momentum_sec_qoq'
    - 'size_sec'
    - 'roa_sec'
    - 'size_factor'
    - 'mkt_rel_sec'
    # growth features
    - 'saleq_yoy'
    - 'saleq_2y'
    - 'niq_yoy'
    - 'niq_2y'
    - 'ltq_yoy'
    - 'ltq_2y'
    - 'dlttq_yoy'
    - 'gpm_yoy'
    - 'gpm_2y'
    - 'roa_yoy'
    - 'roa_2y'
    - 'roi_yoy'
    - 'roi_2y'
    - 'roe_yoy'
    - 'fcf_yoy'
    - 'der_yoy'
    - 'dr_yoy'
    - 'dr_2y'
    - 'ltda_yoy'
    - 'ev_ebitda_yoy'
    - 'ltcr_yoy'
    - 'pe_yoy'
    - 'pe_2y'
    - 'ps_yoy'
    - 'atr_yoy'
    - 'size_yoy'
    # cross-sectional features
    - 'pe_mkt_rank'
    - 'pe_sec_rank'
    - 'ev_ebitda_sec_rank'
    - 'roa_mkt_rank'
    - 'roa_sec_rank'
    - 'saleq_yoy_mkt_rank'
    - 'saleq_yoy_sec_rank'
    - 'fcf_sec_rank'
    - 'der_mkt_rank'
    - 'der_sec_rank'
    - 'price_mom_mkt_rank'
    - 'price_mom_sec_rank'
    - 'price_yoy_mkt_rank'
    - 'price_yoy_sec_rank'
    # sector dummies
    - 'sector_utilities'
    - 'sector_health_care'
    - 'sector_financials'
    - 'sector_consumer_discretionary'
    - 'sector_consumer_staples'
    - 'sector_energy'
    - 'sector_industrials'
    - 'sector_information_technology'
    - 'sector_communication_services'
    - 'sector_materials'
    - 'sector_real_estate'
'targets':
    - 'aggressive_hit'
    - 'balanced_hit'
    - 'relaxed_hit'
'id_col': 'tic'
'date_col': 'tdq'
'min_train_years': 10
'max_splits': 3
'ga':
    'num_generations': 5
    'num_parents_mating': 10
    'sol_per_pop': 60
    'num_genes': 9
    'mutation_percent_genes': 10
    'crossover_probability': 0.8
    'parent_selection_type': "tournament"
    'keep_parents': 3
    'mutation_type': "random"
    'crossover_type': "single_point"
    'init_range_low': [0.01, 100, 3, 2.0, 0.0, 0.6, 0.6, 0.0, 1.0]
    'init_range_high': [0.2, 200, 8, 7.0, 0.5, 0.9, 0.9, 10.0, 10.0]
    'gene_space': [
        {"low": 0.01, "high": 0.2, "step": 0.01},
        {"low": 100, "high": 200, "step": 25},
        {"low": 3, "high": 8, "step": 1},
        {"low": 2.0, "high": 7.0, "step": 0.5},
        {"low": 0.0, "high": 0.5, "step": 0.05},
        {"low": 0.6, "high": 0.9, "step": 0.05},
        {"low": 0.6, "high": 0.9, "step": 0.05},
        {"low": 0.0, "high": 10.0, "step": 0.5},
        {"low": 1.0, "high": 10.0, "step": 0.5},
    ]
