'features':
    # insider trading features
    - 'insider_balance'
    # volume features
    - 'mkt_rel'
    - 'volume_ma20'
    - 'volume_ma50'
    - 'volume_ratio'
    # volatility features
    - 'vol_mom'
    - 'vol_qoq'
    - 'vol_sos'
    - 'vol_yoy'
    - 'vol_2y'
    - 'rel_vol_month'
    - 'rel_vol_quarter'
    - 'rel_vol_year'
    - 'rel_vol_2year'
    # price growth features
    - 'price_mom'
    - 'price_qoq'
    - 'price_yoy'
    - 'price_2y'
    - 'price_risk_quarter'
    - 'price_risk_semester'
    - 'price_risk_year'
    - 'price_risk_2year'
    # technical features
    - 'rsi_14d'
    - 'rsi_30d'
    - 'rsi_60d'
    - 'rsi_90d'
    - 'momentum_month'
    - 'momentum_quarter'
    - 'momentum_year'
    - 'momentum_2year'
    - 'ma20_distance'
    - 'ma50_distance'
    # market trend features
    - 'index_mom'
    - 'index_qoq'
    - 'index_sos'
    - 'index_yoy'
    - 'index_2y'
    - 'fear_ma30'
    - 'high_fear'
    - 'low_fear'
    # financial features
    - 'gpm'
    - 'roa'
    - 'roe'
    - 'ebitdam'
    - 'size'
    - 'earnings_vol'
    - 'margin_vol'
    # price - fundamentals
    - 'earn_drift'
    - 'pe'
    - 'pb'
    - 'ps'
    - 'ev_ebitda'
    - 'f_score'
    # sector features
    - 'pe_sec'
    - 'momentum_sec_yoy'
    - 'momentum_sec_qoq'
    - 'size_sec'
    - 'roa_sec'
    - 'size_factor'
    - 'mkt_rel_sec'
    # growth features
    - 'saleq_yoy'
    - 'saleq_2y'
    - 'niq_yoy'
    - 'niq_2y'
    - 'ltq_yoy'
    - 'ltq_2y'
    - 'dlttq_yoy'
    - 'gpm_yoy'
    - 'gpm_2y'
    - 'roa_yoy'
    - 'roa_2y'
    - 'roi_yoy'
    - 'roi_2y'
    - 'roe_yoy'
    - 'fcf_yoy'
    - 'der_yoy'
    - 'dr_yoy'
    - 'dr_2y'
    - 'ltda_yoy'
    - 'ev_ebitda_yoy'
    - 'ltcr_yoy'
    - 'pe_yoy'
    - 'pe_2y'
    - 'ps_yoy'
    - 'atr_yoy'
    - 'size_yoy'
    - 'roa_sec_qoq'
    - 'roa_sec_yoy'
    # sector dummies
    - 'sector_utilities'
    - 'sector_health_care'
    - 'sector_financials'
    - 'sector_consumer_discretionary'
    - 'sector_consumer_staples'
    - 'sector_energy'
    - 'sector_industrials'
    - 'sector_information_technology'
    - 'sector_communication_services'
    - 'sector_materials'
    - 'sector_real_estate'
'targets':
    - 'risk_return_3Q_hit'
    - 'risk_return_4Q_hit'
    - 'fwd_return_3Q_hit'
    - 'fwd_return_4Q_hit'
'id_col': 'tic'
'date_col': 'tdq'
'min_train_years': 10
'max_splits': 3
'ga':
    'num_generations': 75
    'num_parents_mating': 12
    'sol_per_pop': 60
    'num_genes': 8
    'mutation_percent_genes': 15
    'crossover_probability': 0.8
    'parent_selection_type': "tournament"
    'keep_parents': 8
    'mutation_type': "random"
    'crossover_type': "single_point"
    'init_range_low': [0.001, 2, 2, 0.0, 0.5, 0.5, 0.0, 0.0]
    'init_range_high': [0.3, 8, 7, 0.5, 0.9, 0.9, 5.0, 5.0]
    'gene_space': [
        {"low": 0.001, "high": 0.3},
        {"low": 2, "high": 8},
        {"low": 2, "high": 7},
        {"low": 0.0 , "high": 0.5},
        {"low": 0.5, "high": 0.9},
        {"low": 0.5, "high": 0.9},
        {"low": 0.0, "high": 5.0},
        {"low": 0.0, "high": 5.0},
    ]
