'features':
    # insider trading features
    - 'n_purch'
    - 'n_sales'
    - 'insider_balance'
    # market momentum and volatility features
    - 'volume_ma20'
    - 'volume_ma50'
    - 'price_mom'
    - 'price_qoq'
    - 'price_yoy'
    - 'price_2y'
    - 'rsi_14d'
    - 'rsi_30d'
    - 'rsi_60d'
    - 'rsi_90d'
    - 'rsi_1y'
    - 'vol_mom'
    - 'vol_qoq'
    - 'vol_yoy'
    - 'rel_vol_mom'
    - 'rel_vol_qoq'
    - 'rel_vol_yoy'
    - 'momentum_mom'
    - 'momentum_qoq'
    - 'momentum_yoy'
    - 'momentum_2y'
    - 'fear_ma30'
    - 'high_fear'
    - 'low_fear'
    # financial features
    - 'gpm'
    - 'roa'
    - 'roe'
    - 'ebitdam'
    - 'size'
    # hybrid
    - 'earn_drift'
    - 'pe'
    - 'pb'
    - 'ps'
    - 'ev_ebitda'
    - 'f_score'
    # growth features
    - 'saleq_yoy'
    - 'saleq_2y'
    - 'niq_yoy'
    - 'niq_2y'
    - 'ltq_yoy'
    - 'ltq_2y'
    - 'dlttq_yoy'
    - 'gpm_yoy'
    - 'gpm_2y'
    - 'roa_yoy'
    - 'roa_2y'
    - 'roi_yoy'
    - 'roi_2y'
    - 'roe_yoy'
    - 'fcf_yoy'
    - 'cr_yoy'
    - 'qr_yoy'
    - 'der_yoy'
    - 'dr_yoy'
    - 'dr_2y'
    - 'ltda_yoy'
    - 'ev_ebitda_yoy'
    - 'ltcr_yoy'
    - 'pe_yoy'
    - 'pe_2y'
    - 'pb_yoy'
    - 'ps_yoy'
    - 'atr_yoy'
    # sector dummies
    - 'sector_utilities'
    - 'sector_health_care'
    - 'sector_financials'
    - 'sector_consumer_discretionary'
    - 'sector_consumer_staples'
    - 'sector_energy'
    - 'sector_industrials'
    - 'sector_information_technology'
    - 'sector_communication_services'
    - 'sector_materials'
    - 'sector_real_estate'
'target': 'fsharpe_ratio'
'id_col': 'tic'
'date_col': 'tdq'
'min_train_years': 10
'max_splits': 1
'ga':
    'num_generations': 50
    'num_parents_mating': 10
    'sol_per_pop': 50
    'num_genes': 9
    'mutation_percent_genes': 15
    'crossover_probability': 0.8
    'parent_selection_type': "tournament"
    'keep_parents': 5
    'mutation_type': "random"
    'crossover_type': "single_point"
    'init_range_low': [0.001, 50, 2, 1, 0, 0.5, 0.5, 0, 0]
    'init_range_high': [0.3, 800, 10, 10, 5, 1, 1, 6, 6]
    'gene_space': [
        {"low": 0.001, "high": 0.3},
        {"low": 50, "high": 800},
        {"low": 2, "high": 10},
        {"low": 1, "high": 10},
        {"low": 0, "high": 5},
        {"low": 0.5, "high": 1},
        {"low": 0.5, "high": 1},
        {"low": 0, "high": 6},
        {"low": 0, "high": 6},
    ]
