'base_date': '2005-01-01'
'crsp_columns':
    - 'gvkey'
    - 'tic'
    - 'datadate'
    - 'fyearq'
    - 'fqtr'
    - 'datafmt'
    - 'indfmt'
    - 'rdq'
    - 'saleq'
    - 'cogsq'
    - 'xsgaq'
    - 'niq'
    - 'dpq'
    - 'txtq'
    - 'xintq'
    - 'cheq'
    - 'invtq'
    - 'rectq'
    - 'actq'
    - 'ppentq'
    - 'atq'
    - 'lctq'
    - 'dlttq'
    - 'ltq'
    - 'seqq'
    - 'req'
    - 'oancfy'
    - 'ivncfy'
    - 'fincfy'
    - 'icaptq'
    - 'capxy'
    - 'cshoq'
    - 'dvy'
'macrotrends':
    'income_statement':
        'field_name': 'datadate'
        'Revenue': 'saleq'
        'Cost Of Goods Sold': 'cogsq'
        'SG&A Expenses': 'xsgaq'
        'Net Income': 'niq'
        'EBITDA': 'ebitdaq'
        'Shares Outstanding': 'cshoq'
    'balance_sheet':
        'field_name': 'datadate'
        'Total Current Assets': 'actq'
        'Total Assets': 'atq'
        'Cash On Hand': 'cheq'
        'Receivables': 'rectq'
        'Inventory': 'invtq'
        'Property, Plant, And Equipment': 'ppentq'
        'Total Current Liabilities': 'lctq'
        'Long Term Debt': 'dlttq'
        'Total Liabilities': 'ltq'
        'Retained Earnings (Accumulated Deficit)': 'req'
        'Share Holder Equity': 'seqq'
    'cash_flow':
        'field_name': 'datadate'
        'Cash Flow From Operating Activities': 'oancfq'
        'Cash Flow From Investing Activities': 'ivncfq'
        'Cash Flow From Financial Activities': 'fincfq'
        'Common Stock Dividends Paid': 'dvq'
    'ratios':
        'field_name': 'datadate'
        'ROI - Return On Investment': 'icaptq'
'yahoo':
    'index': 'datadate'
    'Total Revenue': 'saleq'
    'Cost Of Revenue': 'cogsq'
    'Selling General And Administration': 'xsgaq'
    'Net Income': 'niq'
    'Normalized EBITDA': 'ebitdaq'
    'Ordinary Shares Number': 'cshoq'
    'Current Assets': 'actq'
    'Total Assets': 'atq'
    'Cash Cash Equivalents And Short Term Investments': 'cheq'
    'Receivables': 'rectq'
    'Inventory': 'invtq'
    'Net PPE': 'ppentq'
    'Current Liabilities': 'lctq'
    'Long Term Debt': 'dlttq'
    'Total Liabilities Net Minority Interest': 'ltq'
    'Retained Earnings': 'req'
    'Stockholders Equity': 'seqq'
    'Operating Cash Flow': 'oancfq'
    'Investing Cash Flow': 'ivncfq'
    'Financing Cash Flow': 'fincfq'
    'Common Stock Dividend Paid': 'dvq'
    'Capital Expenditure': 'capxq'
    'Invested Capital': 'icaptq'
'yahoo_info':
    'overallRisk': 'risk'
    'beta': 'beta'
    'volume': 'volume'
    'trailingPE': 'trailing_pe'
    'forwardPE': 'forward_pe'
    'trailingPegRatio': 'trailing_peg'
    'pegRatio': 'peg'
    'trailingEps': 'trailing_eps'
    'forwardEps': 'forward_eps'
    'priceToBook': 'price_book'
    'marketCap': 'market_cap'
    'currency': 'currency'
    'sharesOutstanding': 'shares_outstanding'
    'enterpriseValue': 'enterprise_value'
    'shortRatio': 'short_ratio'
    'currentPrice': 'curr_price'
    '52WeekChange': 'fiftytwo_wc'
    'targetLowPrice': 'target_low'
    'targetHighPrice': 'target_high'
    'targetMeanPrice': 'target_mean'
