'schema':
    'stock':
        - 'tic'
        - 'name'
        - 'sector'
        - 'last_update'
        - 'spx_status'
        - 'active'
    'info':
        - 'tic'
        - 'risk'
        - 'beta'
        - 'volume'
        - 'trailing_pe'
        - 'forward_pe'
        - 'trailing_peg'
        - 'peg'
        - 'trailing_eps'
        - 'forward_eps'
        - 'price_book'
        - 'market_cap'
        - 'currency'
        - 'shares_outstanding'
        - 'enterprise_value'
        - 'short_ratio'
        - 'curr_price'
        - 'fiftytwo_wc'
        - 'rec_key'
        - 'target_low'
        - 'target_high'
        - 'target_mean'
    'market':
        - 'tic'
        - 'date'
        - 'close'
        - 'adj_close'
        - 'volume'
    'financial':
        - 'tic'
        - 'datadate'
        - 'rdq'
        - 'saleq'
        - 'cogsq'
        - 'xsgaq'
        - 'niq'
        - 'ebitdaq'
        - 'cshoq'
        - 'actq'
        - 'atq'
        - 'cheq'
        - 'rectq'
        - 'invtq'
        - 'ppentq'
        - 'lctq'
        - 'dlttq'
        - 'ltq'
        - 'req'
        - 'seqq'
        - 'oancfq'
        - 'ivncfq'
        - 'fincfq'
        - 'dvq'
        - 'capxq'
        - 'icaptq'
        - 'surprise_pct'
    'insider':
        - 'tic'
        - 'filling_date'
        - 'trade_date'
        - 'owner_name'
        - 'title'
        - 'transaction_type'
        - 'last_price'
        - 'qty'
        - 'shares_held'
        - 'owned'
        - 'value'
    'sp500':
        - 'date'
        - 'close'
        - 'volume'
    'vix':
        - 'date'
        - 'close'
