'features':
    - 'val_purch'
    - 'val_sales'
    - 'rsi_14d'
    - 'rsi_30d'
    - 'rsi_60d'
    - 'rsi_90d'
    - 'rsi_1y'
    - 'vol_m'
    - 'vol_q'
    - 'vol_y'
    - 'momentum_mom'
    - 'momentum_qoq'
    - 'momentum_yoy'
    - 'price_mom'
    - 'price_qoq'
    - 'price_yoy'
    - 'ni_qoq'
    - 'ni_yoy'
    - 'ni_2y'
    - 'ltq_qoq'
    - 'ltq_yoy'
    - 'ltq_2y'
    - 'dlttq_yoy'
    - 'rev_qoq'
    - 'rev_yoy'
    - 'gpm'
    - 'gpm_qoq'
    - 'gpm_yoy'
    - 'roa'
    - 'roa_qoq'
    - 'roa_yoy'
    - 'roe'
    - 'roe_qoq'
    - 'roe_yoy'
    - 'fcf_yoy'
    - 'cfm'
    - 'cr_yoy'
    - 'qr_yoy'
    - 'der_yoy'
    - 'dr_yoy'
    - 'ltda_yoy'
    - 'pe'
    - 'pe_qoq'
    - 'pe_yoy'
    - 'ev_ebitda'
    - 'ev_eb_qoq'
    - 'ev_eb_yoy'
    - 'ltcr_yoy'
    - 'itr_yoy'
    - 'rtr_yoy'
    - 'atr_yoy'
'targets':
    - 'freturn'
    - 'adj_freturn'
    - 'fperf'
    - 'adj_fperf'
'seed': 123