'features':
    - 'val_purch'
    - 'val_sales'
    - 'rsi_14d'
    - 'rsi_30d'
    - 'rsi_60d'
    - 'vol_m'
    - 'vol_q'
    - 'momentum_qoq'
    - 'momentum_yoy'
    - 'price_yoy'
    - 'ni_qoq'
    - 'ni_yoy'
    - 'ni_2y'
    - 'rev_qoq'
    - 'rev_yoy'
    - 'gpm_qoq'
    - 'gpm_yoy'
    - 'roa_qoq'
    - 'roa_yoy'
    - 'roe_qoq'
    - 'roe_yoy'
    - 'fcf_qoq'
    - 'fcf_yoy'
    - 'cr_qoq'
    - 'cr_yoy'
    - 'qr_qoq'
    - 'qr_yoy'
    - 'der_qoq'
    - 'der_yoy'
    - 'dr_qoq'
    - 'dr_yoy'
    - 'ltda_yoy'
    - 'pe_qoq'
    - 'pe_yoy'
    - 'ev_eb_qoq'
    - 'ev_eb_yoy'
'targets':
    - 'freturn'
    - 'adj_freturn'
    - 'adj_fperf'