'features':
    # insider trading features
    - 'n_purch'
    - 'n_sales'
    - 'insider_balance'
    # growth, momentum and volatility features
    - 'price_mom'
    - 'price_qoq'
    - 'price_yoy'
    - 'price_2y'
    - 'rsi_14d'
    - 'rsi_30d'
    - 'rsi_60d'
    - 'rsi_90d'
    - 'rsi_1y'
    - 'vol_mom'
    - 'vol_qoq'
    - 'vol_yoy'
    - 'rel_vol_mom'
    - 'rel_vol_qoq'
    - 'rel_vol_yoy'
    - 'momentum_mom'
    - 'momentum_qoq'
    - 'momentum_yoy'
    - 'momentum_2y'
    # financial features
    - 'gpm'
    - 'roa'
    - 'roe'
    - 'ebitdam'
    - 'cr'
    - 'qr'
    - 'csr'
    - 'dr'
    - 'debitda'
    - 'ltda'
    - 'ltcr'
    - 'itr'
    - 'rtr'
    - 'atr'
    - 'cfm'
    - 'size'
    # hybrid
    - 'earn_drift'
    - 'pe'
    - 'pb'
    - 'ps'
    - 'ev_ebitda'
    # growth features
    - 'saleq_yoy'
    - 'saleq_2y'
    - 'ni_yoy'
    - 'ni_2y'
    - 'ltq_yoy'
    - 'ltq_2y'
    - 'dlttq_yoy'
    - 'gpm_yoy'
    - 'roa_yoy'
    - 'roe_yoy'
    - 'fcf_yoy'
    - 'cr_yoy'
    - 'qr_yoy'
    - 'der_yoy'
    - 'dr_yoy'
    - 'ltda_yoy'
    - 'ev_eb_yoy'
    - 'ltcr_yoy'
    - 'pe_yoy'
    - 'pb_yoy'
    - 'ps_yoy'
'targets':
    - 'freturn'
    - 'adj_freturn'
    - 'fperf'
    - 'adj_fperf'
'seed': 100