'features':
    - 'val_purch'
    - 'val_sales'
    - 'rsi_14d'
    - 'rsi_30d'
    - 'rsi_60d'
    - 'rsi_90d'
    - 'rsi_1y'
    - 'vol_m'
    - 'vol_q'
    - 'vol_y'
    - 'momentum_mom'
    - 'momentum_qoq'
    - 'momentum_yoy'
    - 'price_mom'
    - 'price_qoq'
    - 'price_yoy'
    - 'ni_qoq'
    - 'ni_yoy'
    - 'ni_2y'
    - 'ltq_qoq'
    - 'ltq_yoy'
    - 'ltq_2y'
    - 'dlttq_yoy'
    - 'rev_qoq'
    - 'rev_yoy'
    - 'gpm'
    - 'roa'
    - 'roe'
    - 'ebitdam'
    - 'cr'
    - 'qr'
    - 'csr'
    - 'dr'
    - 'der'
    - 'debitda'
    - 'ltda'
    - 'ltcr'
    - 'itr'
    - 'rtr'
    - 'atr'
    - 'cfm'
    - 'size'
    - 'pe'
    - 'ev_ebitda'
'targets':
    - 'freturn'
    - 'adj_freturn'
    - 'fperf'
    - 'adj_fperf'
'seed': 123