'base_date': '2005-01-01'
'crsp_columns':
    - 'gvkey'
    - 'tic'
    - 'datadate'
    - 'fyearq'
    - 'fqtr'
    - 'datafmt'
    - 'indfmt'
    - 'rdq'
    - 'saleq' 
    - 'cogsq'  
    - 'xsgaq'
    - 'niq'
    - 'dpq'
    - 'txtq'
    - 'xintq' 
    - 'cheq'
    - 'invtq'
    - 'rectq'
    - 'actq'
    - 'ppentq' # Property Plant and Equipment - Total (Net)
    - 'atq' # Total assets
    - 'lctq' # Total current liabilities
    - 'dlttq' # Total long term Debt
    - 'ltq' # Total liabilities,
    - 'seqq' # Total Shareholders Equity
    - 'req' # Retained Earnings
    - 'oancfy' # Cumulative Yearly CF from Operating Activities
    - 'ivncfy' # Cumulative Yealy CF from Investing Activities
    - 'fincfy' # Cumulative Yealy CF from Financial Activities
    - 'icaptq' # Invested capital
    - 'capxy' # Capital Expenditures
    - 'cshoq' # Common Shares Outstanding
    - 'dvy'
'macrotrends':
    'income_statement':
        'field_name': 'datadate'
        'Revenue': 'saleq'
        'Cost Of Goods Sold': 'cogsq'
        'SG&A Expenses': 'xsgaq'
        'Net Income': 'niq'
        'EBITDA': 'ebitdaq'
        'Shares Outstanding': 'cshoq'
    'balance_sheet':
        'field_name': 'datadate'
        'Total Current Assets': 'actq'
        'Total Assets': 'atq'
        'Cash On Hand': 'cheq'
        'Receivables': 'rectq'
        'Inventory': 'invtq'
        'Property, Plant, And Equipment': 'ppentq'
        'Total Current Liabilities': 'lctq'
        'Long Term Debt': 'dlttq'
        'Total Liabilities': 'ltq'
        'Retained Earnings (Accumulated Deficit)': 'req'
        'Share Holder Equity': 'seqq'
    'cash_flow':
        'field_name': 'datadate'
        'Cash Flow From Operating Activities': 'oancfq'
        'Cash Flow From Investing Activities': 'ivncfq'
        'Cash Flow From Financial Activities': 'fincfq'
        'Common Stock Dividends Paid': 'dvq'
    'ratios':
        'field_name': 'datadate'
        'ROI - Return On Investment': 'icaptq'
'yahoo':
    'index': 'datadate'
    'Total Revenue': 'saleq'
    'Cost Of Revenue': 'cogsq'
    'Selling General And Administration': 'xsgaq'
    'Net Income': 'niq'
    'Normalized EBITDA': 'ebitdaq'
    'Ordinary Shares Number': 'cshoq'
    'Current Assets': 'actq'
    'Total Assets': 'atq'
    'Cash Cash Equivalents And Short Term Investments': 'cheq'
    'Receivables': 'rectq'
    'Inventory': 'invtq'
    'Net PPE': 'ppentq'
    'Current Liabilities': 'lctq'
    'Long Term Debt': 'dlttq'
    'Total Liabilities Net Minority Interest': 'ltq'
    'Retained Earnings': 'req'
    'Stockholders Equity': 'seqq'
    'Operating Cash Flow': 'oancfq'
    'Investing Cash Flow': 'ivncfq'
    'Financing Cash Flow': 'fincfq'
    'Common Stock Dividend Paid': 'dvq'
    'Capital Expenditure': 'capxq'
    'Invested Capital': 'icaptq'
'db':
    'stocks':
        - 'tic'
        - 'name'
        - 'sector'
        - 'last_update'
        - 'spx_status'
        - 'active'
    'metadata':
        - 'tic'
        - 'shares_outstanding'
        - 'enterprise_value'
        - 'rec_key'
        - 'forward_pe'
    'market':
        - 'tic'
        - 'date'
        - 'close'
        - 'adj_close'
        - 'volume'
    'financials':
        - 'tic'
        - 'datadate'
        - 'rdq'
        - 'saleq' 
        - 'cogsq'
        - 'xsgaq'
        - 'niq'
        - 'ebitdaq'
        - 'cshoq'
        - 'actq'
        - 'atq' 
        - 'cheq'
        - 'rectq' 
        - 'invtq'
        - 'ppentq'
        - 'lctq'
        - 'dlttq' 
        - 'ltq' 
        - 'req'
        - 'seqq'
        - 'oancfq'
        - 'ivncfq'
        - 'fincfq'
        - 'dvq' 
        - 'capxq' 
        - 'icaptq'
        - 'surprise_pct'
    'insider':
        - 'tic'
        - 'filling_date' 
        - 'trade_date'
        - 'owner_name'
        - 'title'
        - 'transaction_type'
        - 'last_price'
        - 'qty'
        - 'shares_held'
        - 'owned'
        - 'value'
    'sp500':
        - 'date'
        - 'close'
        - 'adj_close'
        - 'volume'
'variables':
    - 'pe'
    - 'pb'
    - 'eps'
    - 'roa'
    - 'roe'
    - 'ev_ebitda'
    - 'sale_g1'
    - 'rsi_9'
    - 'rsi_30'

